# Generated by Django 5.0.3 on 2024-03-13 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_ordered",
            field=models.DateTimeField(verbose_name=datetime.datetime.today),
        ),
    ]
